# coding: utf-8

"""
    kameleo-local-api

    You can use the following API endpoints to communicate with the local running Kameleo programmatically.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AudioSpoofingType(str, Enum):
    """
    Specifies how the audio will be spoofed. Possible values:  'noise': Add some noise to the Audio generation  'block': Completely block the Audio API  'off': Turn off the spoofing, use the original settings
    """

    """
    allowed enum values
    """
    OFF = 'off'
    NOISE = 'noise'
    BLOCK = 'block'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AudioSpoofingType from a JSON string"""
        return cls(json.loads(json_str))


