# coding: utf-8

"""
    kameleo-local-api

    You can use the following API endpoints to communicate with the local running Kameleo programmatically.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from kameleo.local_api_client.models.quota_statistics import QuotaStatistics
from typing import Optional, Set
from typing_extensions import Self

class RunningProfilesStatistics(BaseModel):
    """
    RunningProfilesStatistics
    """ # noqa: E501
    automated: Optional[QuotaStatistics] = Field(default=None, description="Quota usage of the profiles that are running with an automation framework.")
    manual: Optional[QuotaStatistics] = Field(default=None, description="Quota usage of the profiles that are running manually (were started from GUI or API).")
    total: Optional[QuotaStatistics] = Field(default=None, description="Quota usage of the profiles that are running either manually or with an automation framework.")
    __properties: ClassVar[List[str]] = ["automated", "manual", "total"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RunningProfilesStatistics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of automated
        if self.automated:
            _dict['automated'] = self.automated.to_dict()
        # override the default output from pydantic by calling `to_dict()` of manual
        if self.manual:
            _dict['manual'] = self.manual.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total
        if self.total:
            _dict['total'] = self.total.to_dict()
        # set to None if automated (nullable) is None
        # and model_fields_set contains the field
        if self.automated is None and "automated" in self.model_fields_set:
            _dict['automated'] = None

        # set to None if manual (nullable) is None
        # and model_fields_set contains the field
        if self.manual is None and "manual" in self.model_fields_set:
            _dict['manual'] = None

        # set to None if total (nullable) is None
        # and model_fields_set contains the field
        if self.total is None and "total" in self.model_fields_set:
            _dict['total'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RunningProfilesStatistics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "automated": QuotaStatistics.from_dict(obj["automated"]) if obj.get("automated") is not None else None,
            "manual": QuotaStatistics.from_dict(obj["manual"]) if obj.get("manual") is not None else None,
            "total": QuotaStatistics.from_dict(obj["total"]) if obj.get("total") is not None else None
        })
        return _obj


