# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ScreenSpoofingTypeScreenSizeMultiLevelChoice(Model):
    """ScreenSpoofingTypeScreenSizeMultiLevelChoice.

    All required parameters must be populated in order to send to Azure.

    :param value: Required. Possible values include: 'automatic', 'manual',
     'off'
    :type value: str or ~kameleo.local_api_client.models.enum
    :param extra: The screen size of the device in pixels. For example:
     1920x1080
    :type extra: str
    """

    _validation = {
        'value': {'required': True},
    }

    _attribute_map = {
        'value': {'key': 'value', 'type': 'str'},
        'extra': {'key': 'extra', 'type': 'str'},
    }

    def __init__(self, *, value, extra: str=None, **kwargs) -> None:
        super(ScreenSpoofingTypeScreenSizeMultiLevelChoice, self).__init__(**kwargs)
        self.value = value
        self.extra = extra
