# coding: utf-8

"""
    kameleo-local-api

    You can use the following API endpoints to communicate with the local running Kameleo programmatically.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ScreenSpoofingType(str, Enum):
    """
    Specifies how the screen will be spoofed. Possible values:  'automatic': Automatically override the screen resolution based on the fingerprint.  'manual': Manually override the screen resolution.  'off': Turn off the spoofing, use the original settings.
    """

    """
    allowed enum values
    """
    AUTOMATIC = 'automatic'
    MANUAL = 'manual'
    OFF = 'off'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ScreenSpoofingType from a JSON string"""
        return cls(json.loads(json_str))


