# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class TestProxyRequest(Model):
    """TestProxyRequest.

    All required parameters must be populated in order to send to Azure.

    :param value: Required. Possible values include: 'none', 'http', 'socks5',
     'ssh'
    :type value: str or ~kameleo.local_api_client.models.enum
    :param extra: Required.
    :type extra: ~kameleo.local_api_client.models.Server
    """

    _validation = {
        'value': {'required': True},
        'extra': {'required': True},
    }

    _attribute_map = {
        'value': {'key': 'value', 'type': 'str'},
        'extra': {'key': 'extra', 'type': 'Server'},
    }

    def __init__(self, *, value, extra, **kwargs) -> None:
        super(TestProxyRequest, self).__init__(**kwargs)
        self.value = value
        self.extra = extra
