# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class WebRtcSpoofingTypeWebRtcSpoofingOptionsMultiLevelChoice(Model):
    """WebRtcSpoofingTypeWebRtcSpoofingOptionsMultiLevelChoice.

    All required parameters must be populated in order to send to Azure.

    :param value: Required. Possible values include: 'automatic', 'manual',
     'block', 'off'
    :type value: str or ~kameleo.local_api_client.models.enum
    :param extra:
    :type extra: ~kameleo.local_api_client.models.WebRtcSpoofingOptions
    """

    _validation = {
        'value': {'required': True},
    }

    _attribute_map = {
        'value': {'key': 'value', 'type': 'str'},
        'extra': {'key': 'extra', 'type': 'WebRtcSpoofingOptions'},
    }

    def __init__(self, *, value, extra=None, **kwargs) -> None:
        super(WebRtcSpoofingTypeWebRtcSpoofingOptionsMultiLevelChoice, self).__init__(**kwargs)
        self.value = value
        self.extra = extra
