# coding: utf-8

"""
    kameleo-local-api

    You can use the following API endpoints to communicate with the local running Kameleo programmatically.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class WebglMetaSpoofingType(str, Enum):
    """
    Specifies how the WebGL vendor and renderer will be spoofed. Possible values:  'automatic': The vendor and renderer values comes from the fingerprint.  'manual': Manually configure WebGL metadata. For optimal results, choose a video card model similar to your device's to ensure realistic  profile masking.  'off': Turn off the spoofing, use the original settings
    """

    """
    allowed enum values
    """
    AUTOMATIC = 'automatic'
    MANUAL = 'manual'
    OFF = 'off'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WebglMetaSpoofingType from a JSON string"""
        return cls(json.loads(json_str))


