# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class WebglMeta(Model):
    """WebglMeta.

    All required parameters must be populated in order to send to Azure.

    :param vendor: Required. The UnmaskedVendor field from WebGL context
    :type vendor: str
    :param renderer: The UnmaskedRenderer field from WebGL context
    :type renderer: str
    """

    _validation = {
        'vendor': {'required': True},
    }

    _attribute_map = {
        'vendor': {'key': 'vendor', 'type': 'str'},
        'renderer': {'key': 'renderer', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(WebglMeta, self).__init__(**kwargs)
        self.vendor = kwargs.get('vendor', None)
        self.renderer = kwargs.get('renderer', None)
